// <auto-generated />
namespace PBL3_DanTaPhaiBietSuTa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _1211111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1211111));
        
        string IMigrationMetadata.Id
        {
            get { return "202105031515586_1211111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
